name: CI

on:
    push:
        branches:
            - "main"

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: pnpm/action-setup@v3.0.0
              with:
                  version: latest
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"

            - run: pnpm install # not pnpm ci

            - run: pnpm run build
